name: climbprep
channels:
  - defaults
dependencies:
  - pip
  - python
  - pip:
    - matplotlib
    - nibabel
    - nilearn
    - git+https://github.com/nipy/nitransforms.git@master
    - numpy
    - pandas
    - pymatreader
    - pyyaml
    - scikit-learn
    - scipy
    - fast-poibin
    - seaborn
    - plotly
    - kaleido
    - pyvista
    - dash[diskcache]
    - dash-iconify
    - dash-mantine-components
