name: climbprep
channels:
  - defaults
dependencies:
  - pip
  - python
  - pip:
    - matplotlib
    - nibabel
    - nilearn
    - nitransforms<25
    - numpy
    - pandas
    - pymatreader
    - pyyaml
    - scikit-learn
    - scipy
    - fast-poibin
    - seaborn
    - plotly
    - kaleido
    - choreographer
    - pyvista
    - dash[diskcache]
    - dash-iconify
    - dash-mantine-components
