name: climbprep
channels:
  - defaults
dependencies:
  - pip
  - python
  - pip:
    - matplotlib
    - nibabel
    - nilearn
    - nitransforms
    - numpy
    - pandas
    - pymatreader
    - pyyaml
    - scikit-learn
    - scipy
    - seaborn
